name: API CI
on:
  push:
    paths: ["api/**", ".github/workflows/api-ci.yml"]
  pull_request:
    paths: ["api/**"]

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Import smoke test
        run: |
          python - << 'PY'
          import sys
          print("python:", sys.version)
          import fastapi, pandas
          print("fastapi:", fastapi.__version__)
          print("pandas:", pandas.__version__)
          PY
